name: flask
channels:
  - conda-forge
dependencies:
  - python=3.6.0
  - pip
  - pip:
    - alembic==0.9.3
    - apispec==1.3.3
    - attrs==19.1.0
    - Babel==2.7.0
    - bleach==2.0.0
    - blinker==1.4
    - certifi==2019.6.16
    - click==6.7
    - colorama==0.4.1
    - defusedxml==0.6.0
    - dominate==2.3.1
    - Flask==1.1.1
    - Flask-AppBuilder==2.1.10
    - Flask-Babel==0.12.2
    - Flask-Bootstrap4==4.0.2
    - Flask-HTTPAuth==3.2.3
    - Flask-JWT-Extended==3.21.0
    - Flask-Login==0.4.0
    - Flask-Mail==0.9.1
    - Flask-Migrate==2.0.4
    - Flask-Moment==0.5.1
    - Flask-OpenID==1.2.5
    - Flask-PageDown==0.2.2
    - Flask-Script==2.0.6
    - Flask-SQLAlchemy==2.4.0
    - Flask-WTF==0.14.2
    - html5lib==0.999999999
    - itsdangerous==0.24
    - Jinja2==2.10.1
    - jsonschema==3.0.2
    - Mako==1.0.7
    - Markdown==2.6.8
    - MarkupSafe==1.0
    - marshmallow==2.19.5
    - marshmallow-enum==1.5.1
    - marshmallow-sqlalchemy==0.17.0
    - numpy==1.17.0
    - pandas==0.24.1
    - prison==0.1.2
    - PyJWT==1.7.1
    - pyrsistent==0.15.4
    - python-dateutil==2.6.1
    - python-dotenv==0.6.5
    - python-editor==1.0.3
    - python3-openid==3.1.0
    - pytz==2019.2
    - PyYAML==5.1.2
    - six==1.11.0
    - SQLAlchemy==1.1.11
    - SQLAlchemy-Utils==0.34.2
    - visitor==0.1.3
    - webencodings==0.5.1
    - Werkzeug==0.15.5
    - WTForms==2.1
  
